M48
; DRILL file {KiCad 7.0.2} date Fri Aug 18 20:24:25 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-18T20:24:25-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0709
%
G90
G05
T1
X6.6748Y-1.9079
X6.6748Y-2.0079
X6.6748Y-2.1079
T2
X7.3498Y-2.0079
X7.5407Y-2.0079
T3
X7.338Y-1.8886
X7.5526Y-1.8886
T0
M30
