# Generated by Django 4.2.1 on 2023-05-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batteryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batteryStatus', models.IntegerField()),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='providerPowerUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providerPowerUsage', models.IntegerField()),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='solarPowerUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solarPowerUsage', models.IntegerField()),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='totalPowerUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPowerUsage', models.IntegerField()),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prod', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('auth', models.BooleanField()),
            ],
        ),
    ]
