# Generated by Django 4.2.5 on 2023-10-05 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_mngmnt", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datosdias",
            options={"ordering": ["user", "año", "mes", "dia"]},
        ),
    ]
