# Generated by Django 4.2.4 on 2023-08-22 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_mngmnt", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datos_dias",
            name="voltaje_promedio_dia_red",
        ),
        migrations.RemoveField(
            model_name="datos_dias",
            name="voltaje_promedio_dia_solar",
        ),
        migrations.RemoveField(
            model_name="datos_hora",
            name="voltaje_hora_solar",
        ),
        migrations.AddField(
            model_name="datos_dias",
            name="año",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="datos_dias",
            name="dia",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="datos_dias",
            name="horas_potencia_panel",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="datos_dias",
            name="mes",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="datos_dias",
            name="total_potencia_panel",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="datos_dias",
            name="voltaje_maximo_dia_red",
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name="datos_hora",
            name="año",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="datos_hora",
            name="errores",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="datos_hora",
            name="panel_potencia",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="datos_hora",
            name="solar_ahora",
            field=models.BooleanField(default=None),
        ),
        migrations.CreateModel(
            name="Tiempo_real",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voltaje", models.FloatField(default=None)),
                ("consumo", models.FloatField(default=None)),
                ("solar", models.BooleanField(default=None)),
                ("cargando", models.BooleanField(default=None)),
                ("voltaje_bateria", models.IntegerField(default=None)),
                ("errores", models.BooleanField(default=None)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
