# Generated by Django 4.2.1 on 2023-08-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_mngmnt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Datos_dias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voltaje_promedio_dia", models.FloatField(default=None)),
                ("consumo_promedio_dia", models.FloatField(default=None)),
                ("errores", models.BooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name="Datos_hora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voltaje_hora", models.FloatField(default=None)),
                ("consumo_hora", models.FloatField(default=None)),
                ("dia", models.IntegerField(default=None)),
                ("mes", models.IntegerField(default=None)),
                ("hora", models.IntegerField(default=None)),
                ("solar", models.IntegerField(default=None)),
                ("porcentaje_bateria", models.IntegerField(default=None)),
                ("charging", models.BooleanField(default=None)),
                ("voltaje_bateria", models.IntegerField(default=None)),
                ("product_id", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Emergencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voltaje", models.FloatField(default=None)),
                ("consumo", models.FloatField(default=None)),
                ("dia", models.IntegerField(default=None)),
                ("mes", models.IntegerField(default=None)),
                ("hora", models.IntegerField(default=None)),
                ("voltaje_bajo", models.BooleanField()),
                ("voltaje_alto", models.BooleanField()),
                ("red", models.BooleanField()),
                ("corriente", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Productos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=50)),
                ("conexion", models.GenericIPAddressField()),
            ],
        ),
        migrations.DeleteModel(
            name="Datos",
        ),
        migrations.RemoveField(
            model_name="user_link",
            name="id",
        ),
        migrations.AlterField(
            model_name="user_link",
            name="product_id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
