# Generated by Django 4.2.5 on 2023-09-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_mngmnt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users_tokens",
            name="password_reset_token",
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="users_tokens",
            name="signup_token",
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
