# Generated by Django 4.2.4 on 2023-08-22 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_mngmnt", "0002_remove_datos_dias_voltaje_promedio_dia_red_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datos_dias",
            name="user",
        ),
        migrations.RemoveField(
            model_name="datos_hora",
            name="user",
        ),
        migrations.RemoveField(
            model_name="emergencia",
            name="user",
        ),
        migrations.RemoveField(
            model_name="tiempo_real",
            name="user",
        ),
        migrations.DeleteModel(
            name="User_data",
        ),
        migrations.AddField(
            model_name="datos_dias",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="datos_hora",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="emergencia",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="tiempo_real",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
