# Generated by Django 4.2.5 on 2023-09-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_mngmnt", "0002_alter_users_tokens_password_reset_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users_tokens",
            name="time",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
