# Generated by Django 4.2.4 on 2023-08-22 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_mngmnt", "0003_remove_datos_dias_user_remove_datos_hora_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datos_hora",
            name="user",
        ),
        migrations.AddField(
            model_name="datos_hora",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
